#!/usr/bin/env node
/*
 * Rebuilds the question database from a backup exported by the extension.
 *
 *   node tools/update-db.js path/to/backup.json
 *
 * It updates every place the question set lives:
 *   extension/db.js          — what a fresh install is seeded with
 *   data/answers.json        — the human-readable published copy
 *   extension/background.js  — bumps SEED_VERSION so existing installs top up
 *
 * Accepts either schema: {q, a} (extension export) or {question, answer}.
 * Entries are de-duplicated by question text, ignoring Lithuanian diacritics.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DB_JS = path.join(ROOT, "extension", "db.js");
const ANSWERS = path.join(ROOT, "data", "answers.json");
const BACKGROUND = path.join(ROOT, "extension", "background.js");

// переиспользуем нормализацию расширения, чтобы дедупликация была одинаковой
global.self = global;
require(path.join(ROOT, "extension", "match.js"));
const norm = self.QAMatch.normalize;

function readPairs(file) {
  const arr = JSON.parse(fs.readFileSync(file, "utf8"));
  if (!Array.isArray(arr)) throw new Error(file + ": expected a JSON array");
  return arr
    .map((x) => ({
      q: String((x && (x.q ?? x.question)) || "").trim(),
      a: String((x && (x.a ?? x.answer)) || "").trim(),
    }))
    .filter((x) => x.q);
}

/* Сливает списки по нормализованному тексту вопроса.
   Существующие ответы никогда не перезаписываются — новые данные могут
   только добавить вопрос или заполнить пустой ответ. Так повторный прогон
   скрипта не может незаметно испортить выверенную запись. */
function merge(...lists) {
  const seen = new Map();
  for (const list of lists) {
    for (const item of list) {
      const key = norm(item.q);
      if (!key) continue;
      const prev = seen.get(key);
      if (!prev) seen.set(key, item);
      else if (!prev.a && item.a) prev.a = item.a;
    }
  }
  return [...seen.values()];
}

function writeDbJs(list) {
  const body = list
    .map((x) => "  {q:" + JSON.stringify(x.q) + ", a:" + JSON.stringify(x.a) + "}")
    .join(",\n");
  fs.writeFileSync(
    DB_JS,
    "// Built-in question set.\n" +
      "// Generated by tools/update-db.js — do not edit by hand.\n" +
      "self.QA_SEED = [\n" + body + "\n];\n",
    "utf8"
  );
}

function writeAnswersJson(list) {
  const out = list.map((x) => ({ question: x.q, answer: x.a }));
  fs.writeFileSync(ANSWERS, JSON.stringify(out, null, 2) + "\n", "utf8");
}

function bumpSeedVersion() {
  const src = fs.readFileSync(BACKGROUND, "utf8");
  const m = src.match(/var SEED_VERSION = (\d+);/);
  if (!m) throw new Error("SEED_VERSION not found in background.js");
  const next = Number(m[1]) + 1;
  fs.writeFileSync(
    BACKGROUND,
    src.replace(m[0], "var SEED_VERSION = " + next + ";"),
    "utf8"
  );
  return next;
}

function main() {
  const backup = process.argv[2];
  if (!backup) {
    console.error("usage: node tools/update-db.js <backup.json>");
    process.exit(1);
  }
  if (!fs.existsSync(backup)) {
    console.error("file not found: " + backup);
    process.exit(1);
  }

  const existing = readPairs(ANSWERS);
  const incoming = readPairs(backup);
  const merged = merge(existing, incoming);

  const addedCount = merged.length - existing.length;
  writeDbJs(merged);
  writeAnswersJson(merged);
  const version = bumpSeedVersion();

  console.log("existing:   " + existing.length);
  console.log("in backup:  " + incoming.length);
  console.log("new:        " + addedCount);
  console.log("total:      " + merged.length);
  console.log("SEED_VERSION -> " + version);
  console.log("\nupdated: extension/db.js, data/answers.json, extension/background.js");
}

main();
